# Generated by Django 2.2.7 on 2019-12-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('visit', models.CharField(max_length=200)),
                ('dur', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
